name: grades_journal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.15.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_riverpod: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/main_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/main_icon.png"
